// generated by stringer -type=ValueKind; DO NOT EDIT

package pdf

import "fmt"

const _ValueKind_name = "NullBoolIntegerRealStringNameDictArrayStream"

var _ValueKind_index = [...]uint8{4, 8, 15, 19, 25, 29, 33, 38, 44}

func (i ValueKind) String() string {
	if i < 0 || i >= ValueKind(len(_ValueKind_index)) {
		return fmt.Sprintf("ValueKind(%d)", i)
	}
	hi := _ValueKind_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _ValueKind_index[i-1]
	}
	return _ValueKind_name[lo:hi]
}
